#!/usr/bin/env python3
"""Deterministic original vector artwork. Run --check to validate generated sources."""
import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]

def cross(cx, cy, sx, sy, black):
    # Four flared arms with concave sides, original paths (no copied logo artwork).
    path = 'M -.30,-.5 L .30,-.5 Q .12,-.23 .085,-.085 Q .23,-.12 .5,-.30 L .5,.30 Q .23,.12 .085,.085 Q .12,.23 .30,.5 L -.30,.5 Q -.12,.23 -.085,.085 Q -.23,.12 -.5,.30 L -.5,-.30 Q -.23,-.12 -.085,-.085 Q -.12,-.23 -.30,-.5 Z'
    return f'<path d="{path}" transform="translate({cx:.4f} {cy:.4f}) scale({sx:.4f} {sy:.4f})" fill="{black}"/>'

def build(d):
    red, white, black=(d['palette'][k] for k in ('red','white','black'))
    s=['<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">',f'<rect width="1024" height="1024" fill="{red}"/>']
    wing=d['wing']
    for sign in (-1,1):
        x0,x1=sorted((512+sign*512*f for f in wing['field_semispan_fraction']))
        border=1024*wing['border_width_m']/1.524
        s += [f'<rect x="{x0-border:.4f}" y="0" width="{x1-x0+border*2:.4f}" height="272" fill="{black}"/>',f'<rect x="{x0:.4f}" y="0" width="{x1-x0:.4f}" height="272" fill="{white}"/>',cross(512+sign*512*wing['cross_center_semispan_fraction'],16+224*wing['cross_center_chord_fraction'],1024*wing['cross_size_m']/1.524,224*wing['cross_size_m']/.3048,black)]
    for rib in range(-14,15):
        x=512+rib*d['rib_hints']['pitch_m']*1024/1.524
        s += [f'<path d="M {x:.4f},0 V 272" stroke="{black}" stroke-width="0.8" opacity="{d["rib_hints"]["opacity"]}"/>']
    s += [f'<rect x="16" y="528" width="480" height="464" fill="{white}"/>']
    fin=d['fin']
    s += [cross(32+448*(fin['cross_center_chord_z_m']+.2)/.31,976-432*fin['cross_center_height_m']/.215,448*fin['cross_size_m']/.31,432*fin['cross_size_m']/.215,black)]
    dorsal=d['dorsal']
    w,h=464*dorsal['field_width_m']/.11,464*dorsal['field_length_m']/.12
    s += [f'<rect x="{776-w/2:.4f}" y="{776-h/2:.4f}" width="{w:.4f}" height="{h:.4f}" fill="{white}"/>',cross(776,776,464*dorsal['cross_size_m']/.11,464*dorsal['cross_size_m']/.12,black),'</svg>']
    return '\n'.join(s)+'\n'

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    d=json.loads((HERE/'appearance.json').read_text())
    target=ROOT/'app/aircraft/livery.svg'; source=build(d)
    generated = '# Generated by compile_appearance.py; visual estimates only.\nextends RefCounted\n'
    generated += 'const DATA := ' + json.dumps(d,ensure_ascii=False,indent='\t') + '\n'
    for key,value in d['palette'].items():
        generated += f'const {key.upper()} := Color("{value}")\n'
    generated += 'const SVG_SOURCE := ' + json.dumps(source) + '\n'
    outputs={target:source,ROOT/'app/aircraft/ugly_stik_appearance.gd':generated}
    for path,text in outputs.items():
        if args.check:
            assert path.read_text()==text,f'Stale {path.name}; rerun compile_appearance.py'
        else: path.write_text(text)
    if args.check: print('Appearance source, generated data and SVG match')
if __name__=='__main__':main()
