"""Regenerate sources.json: every external Markdown link cited by the numbered menu research reports.

Usage: python3 docs/research/menu-investigations/build_sources.py
Standard library only. Groups fragments by page (URL without #anchor), keeps each label and the reports citing it.
Source contents are not archived; the reports carry the claims next to each link.
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
LINK = re.compile(r"\[([^\]]+)\]\((https?://[^)\s]+)\)")

pages: dict[str, dict] = {}
reports = sorted(p for p in HERE.glob("[0-9][0-9]-*.md"))
for report in reports:
    for label, url in LINK.findall(report.read_text(encoding="utf-8")):
        page = url.split("#", 1)[0]
        entry = pages.setdefault(page, {"url": page, "labels": [], "reports": []})
        if label not in entry["labels"]:
            entry["labels"].append(label)
        if report.name not in entry["reports"]:
            entry["reports"].append(report.name)

out = {
    "date": "2026-10-05",
    "kind": "cited-primary-source-index",
    "method": "External Markdown citations in the numbered research reports (round 2: 01-10, round 3: 11-22); "
    "fragments grouped by page. Generated by build_sources.py. Source contents are not archived here. "
    "Reports distinguish documentation, code read at pinned commits, probes run on the pinned Godot 4.7.2, "
    "design inference and pending tests.",
    "report_count": len(reports),
    "source_count": len(pages),
    "sources": sorted(pages.values(), key=lambda e: e["url"]),
}
(HERE / "sources.json").write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"{len(reports)} reports, {len(pages)} source pages -> sources.json")
