extends SceneTree
const Sim := preload("res://sim/simulation.gd")
const RB := preload("res://physics/rigid_body.gd")
const M := preload("res://physics/math3d.gd")
func _initialize() -> void:
	var source: Node = Sim.new()
	source.reset(RB.make_state(M.v3(0, 0, -100), M.v3(15, 0, 0), M.q_identity(), M.v3(0, 0, 0)))
	source.step()
	var cp: Dictionary = source.checkpoint()
	var fresh: Node = Sim.new()
	print("fresh restore accepted: ", fresh.restore_checkpoint(cp))
	fresh.step()
	print("fresh continuation: tick=", fresh.tick, " fault=", fresh.fault_reason)
	fresh.free()
	source.state[RB.ATT] = 2.0
	var invalid: Dictionary = source.checkpoint()
	print("unnormalized checkpoint emitted: ", not invalid.is_empty(), " restorable: ", source.can_restore_checkpoint(invalid))
	source.restore_checkpoint(cp)
	invalid = cp.duplicate(true)
	invalid.tick = 9223372036854775807
	print("overflow clock restore accepted: ", source.restore_checkpoint(invalid))
	source.step()
	print("overflow continuation: tick=", source.tick, " fault=", source.fault_reason)
	source.restore_checkpoint(cp)
	source.inertia = PackedFloat64Array([1e-300 * 1e-10, 1, 1, 0, 0, 0])
	invalid = cp.duplicate(true)
	invalid.inertia = source.inertia.duplicate()
	print("nonfinite inverse preflight accepted: ", source.can_restore_checkpoint(invalid))
	print("nonfinite inverse restore accepted: ", source.restore_checkpoint(invalid), " inverse=", source._inertia_inv)
	source.free()
	quit()
