# D10 sensitivity sweep and D8b validation table (plan review #3 tools; kept outside app/ so test.sh never runs them).
# Each unknown is varied in the aircraft DATA (the loader re-derives stall start, κ, inertia…), then the airplane is
# analysed (flight modes) and flown (scripted maneuvers through the real loop).
# D11a (2026-10-06): after the flight repair the loader ties Cnβ to the fin, requires the inventory CG to match the
# flight CG and bounds the gear's ω·dt, so three variants are now made the physical way: fin area (Cnβ with its
# rudder derivatives), the whole mass inventory moved with the CG, and mass with the gear springs scaled alongside
# (same sag and ω; the gear does not act in the air). Adds the Ultra Stick 25e comparison (Dorobantu et al. 2013).
# Run (repo root): $(app/get-godot.sh) --headless --path app --script "$PWD/research/sensitivity/sensitivity.gd"
extends SceneTree

const AD := preload("res://physics/aircraft_data.gd")
const FlightModes := preload("res://physics/flight_modes.gd")
const FlightSession := preload("res://sim/flight_session.gd")
const Maneuvers := preload("res://sim/maneuvers.gd")
const Scenarios := preload("res://sim/scenarios.gd")

const OUTPUTS := ["SP Hz", "SP ζ", "roll τ s", "DR Hz", "DR ζ", "spiral λ 1/s", "roll °/s", "stall m/s", "glide L/D"]

var _session: Node


func _raw() -> Dictionary:
	return JSON.parse_string(FileAccess.get_file_as_string(Scenarios.AIRCRAFT))


## Measures one variant. post(model) may edit the derived model (inertia entries).
## The spiral is reported as its pole λ = −1/τ (> 0 diverges): near neutral, τ passes through infinity and its percent
## change is meaningless, while λ stays small and continuous.
func _measure(raw: Dictionary, post := Callable()) -> Array:
	var data := AD.validate_and_derive(raw)
	if not data.ok:
		return []
	if post.is_valid():
		post.call(data.model)
	var m := FlightModes.analyze(data.model, 15.0)
	_session._apply(data)
	var roll: RefCounted = Maneuvers.fly(_session, Maneuvers.all().roll_15_coordinated)
	var p_max := 0.0
	for r in roll.row_count():
		p_max = maxf(p_max, roll.value(r, "p_radps"))
	var slow: RefCounted = Maneuvers.fly(_session, Maneuvers.all().slow_flight)
	var stall := 0.0
	for r in slow.row_count():
		if slow.value(r, "alt_m") < Maneuvers.SLOW_FLIGHT.altitude - 0.5:
			stall = slow.value(r, "speed_mps")
			break
	var glide: RefCounted = Maneuvers.fly(_session, Maneuvers.all().glide_15)
	var last: int = glide.row_count() - 1
	var r0 := last - 960
	var dn: float = glide.value(last, "north_m") - glide.value(r0, "north_m")
	var de: float = glide.value(last, "east_m") - glide.value(r0, "east_m")
	var sink: float = glide.value(r0, "alt_m") - glide.value(last, "alt_m")
	var ld := sqrt(dn * dn + de * de) / sink
	return [m.short_period.f_hz, m.short_period.zeta, m.roll_tau, m.dutch_roll.f_hz, m.dutch_roll.zeta, -1.0 / m.spiral_tau, rad_to_deg(p_max), stall, ld]


func _initialize() -> void:
	_session = FlightSession.new()
	_session.setup()
	root.add_child(_session)
	print("<!-- Generated by research/sensitivity/sensitivity.gd (D8b, D10, D11a); do not edit. Regenerate after any change to")
	print("the physics or the Stik data: $(app/get-godot.sh) --headless --path app --script \"$PWD/research/sensitivity/sensitivity.gd\" -->\n")
	var base := _measure(_raw())

	# D8b: the sim against the University of Minnesota's flight-identified Ultra Stick 120 (Froude-scaled, same CL).
	var model: Dictionary = AD.load_file(Scenarios.AIRCRAFT).model
	var eq := FlightModes.analyze(model, 13.8)
	print("## D8b validation: sim at 13.8 m/s (same CL as the US120 trim) vs Froude-scaled US120 flight identification\n")
	print("| Mode | US120 band | Ugly Stik sim | Ratio |\n| --- | --- | --- | --- |")
	print("| Short period | 1.30 Hz, ζ 0.55 | %.2f Hz, ζ %.2f | %.2f× |" % [eq.short_period.f_hz, eq.short_period.zeta, eq.short_period.f_hz / 1.30])
	print("| Roll τ | 0.116 s | %.3f s | %.2f× faster |" % [eq.roll_tau, 0.116 / eq.roll_tau])
	print("| Dutch roll | 0.57 Hz, ζ 0.31 | %.2f Hz, ζ %.2f | %.2f× |" % [eq.dutch_roll.f_hz, eq.dutch_roll.zeta, eq.dutch_roll.f_hz / 0.57])
	print("| Spiral | stable, τ 4.3 s | %s, τ %.1f s | — |\n" % ["stable" if eq.spiral_tau > 0 else "unstable", eq.spiral_tau])
	_print_25e(model)
	var a: Dictionary = model.aero
	var dr: float = deg_to_rad(model.controls.throw_deg.rudder)
	print("Full-rudder steady sideslip (linear): β = Cnδr·δr / Cnβ = %.0f°\n" % rad_to_deg(absf(a.Cndr) * dr / a.Cnb))

	# D10: each unknown ±20 % (CG ±0.02 m ≈ 6.6 % MAC).
	var cases := [
		["Clp", func(r: Dictionary, k: float) -> void: r.aero.coefficients.Clp.value *= k],
		["Cmq", func(r: Dictionary, k: float) -> void: r.aero.coefficients.Cmq.value *= k],
		["Cma", func(r: Dictionary, k: float) -> void: r.aero.coefficients.Cma.value *= k],
		["fin area (Cnβ, rudder)", func(r: Dictionary, k: float) -> void:
			r.aero.surfaces.vertical.area.value *= k
			for key in ["Cnb", "CYdr", "Cndr", "Cldr"]: # all proportional to the fin area in the loader's consistency rule
				r.aero.coefficients[key].value *= k],
		["Cnr", func(r: Dictionary, k: float) -> void: r.aero.coefficients.Cnr.value *= k],
		["CD0", func(r: Dictionary, k: float) -> void: r.aero.coefficients.CD0.value *= k],
		["CL_max", func(r: Dictionary, k: float) -> void: r.aero.envelope.CL_max.value *= k],
		["servo time", func(r: Dictionary, k: float) -> void: r.controls.servo_full_throw_time.value *= k],
		["mass (±15 %, gear scaled)", func(r: Dictionary, k: float) -> void:
			var km := 1.0 + 0.75 * (k - 1.0) # ±15 %: +20 % leaves the plausible mass range [2.3, 3.4] kg
			for part in r.inventory:
				part.mass.value *= km
			for contact in r.get("landing_gear", {}).get("contacts", []):
				contact.stiffness.value *= km
				contact.damping.value *= km],
		["CG (±0.02 m)", func(r: Dictionary, k: float) -> void:
			var dx := 0.1 * (k - 1.0) # the whole inventory moves with the CG: same mass and inertia about the CG
			r.balance.plan_cg.value[0] += dx
			for part in r.inventory:
				part.position.value[0] += dx],
	]
	var inertia_cases := [["Ixx", 0], ["Iyy", 1], ["Izz", 2]]
	var rows := []
	for c in cases:
		var res := []
		for k in [0.8, 1.2]:
			var raw := _raw()
			c[1].call(raw, k)
			res.append(_measure(raw))
		rows.append([c[0], res])
	for c in inertia_cases:
		var res := []
		for k in [0.8, 1.2]:
			var idx: int = c[1]
			res.append(_measure(_raw(), func(m: Dictionary) -> void:
				var j: PackedFloat64Array = m.inertia.duplicate()
				j[idx] *= k
				m.inertia = j))
		rows.append([c[0], res])
	print("## D10 sensitivity: % change of each output for the parameter at −20 % / +20 %\n")
	print("Baseline: " + ", ".join(range(OUTPUTS.size()).map(func(i): return "%s %.3f" % [OUTPUTS[i], base[i]])) + "\n")
	print("| Parameter | " + " | ".join(OUTPUTS) + " | largest |")
	print("| --- " + "| --- ".repeat(OUTPUTS.size() + 1) + "|")
	var ranked := []
	for row in rows:
		var cells := []
		var worst := 0.0
		for i in OUTPUTS.size():
			var parts := []
			for side in 2:
				if row[1][side].is_empty():
					parts.append("refused") # the loader rejected the variant (e.g. mass outside its plausible range)
				else:
					var pct: float = 100.0 * (row[1][side][i] - base[i]) / base[i]
					parts.append("%+.0f" % pct)
					worst = maxf(worst, absf(pct))
			cells.append(" / ".join(parts))
		ranked.append([worst, "| %s | %s | %.0f %% |" % [row[0], " | ".join(cells), worst]])
	ranked.sort_custom(func(x, y): return x[0] > y[0])
	for r in ranked:
		print(r[1])
	quit()


## D11a: the Ultra Stick 25e, flight-identified by Dorobantu et al. 2013 (AIAA JA preprint, UMN; read for plan review #4,
## docs/research/roadmap-investigations/08-validation-flight-testing.md): 19 m/s, m 1.959 kg, S 0.31 m², b 1.27 m,
## c 0.25 m, so CL 0.28. It is Reynolds-matched to the Stik (≈ 3.2e5). Compared nondimensionally (ω·L/2V, L = c in pitch
## and b laterally) with the Stik flown at the same CL, because the relative densities differ.
func _print_25e(model: Dictionary) -> void:
	var ref := { V = 19.0, m = 1.959, S = 0.31, b = 1.27, c = 0.25, sp_wn = 16.33, sp_zeta = 0.83, roll = 12.53, dr_wn = 4.96, dr_zeta = 0.33 }
	var rho := 1.225
	var cl: float = 2.0 * ref.m * 9.80665 / (rho * ref.V * ref.V * ref.S)
	var S: float = model.reference.S
	var b: float = model.reference.b
	var c: float = model.reference.c
	var V := sqrt(2.0 * model.mass_kg * 9.80665 / (rho * S * cl))
	var eq := FlightModes.analyze(model, V)
	if not eq.ok:
		print("25e comparison: %s\n" % eq.message)
		return
	var sp_wn: float = TAU * eq.short_period.f_hz
	var dr_wn: float = TAU * eq.dutch_roll.f_hz
	var roll: float = 1.0 / eq.roll_tau
	var nd := func(w: float, length: float, speed: float) -> float: return w * length / (2.0 * speed)
	print("## D11a validation: sim at %.1f m/s vs the flight-identified Ultra Stick 25e (19 m/s), both at CL %.2f, nondimensional\n" % [V, cl])
	print("| Mode | 25e flight ID | 25e ω·L/2V | Ugly Stik sim | sim ω·L/2V | Sim / 25e |\n| --- | --- | --- | --- | --- | --- |")
	print("| Short period (L = c) | %.2f rad/s, ζ %.2f | %.4f | %.2f rad/s, ζ %.2f | %.4f | %.2f× |" % [ref.sp_wn, ref.sp_zeta, nd.call(ref.sp_wn, ref.c, ref.V),
		sp_wn, eq.short_period.zeta, nd.call(sp_wn, c, V), nd.call(sp_wn, c, V) / nd.call(ref.sp_wn, ref.c, ref.V)])
	print("| Roll pole (L = b) | %.2f 1/s | %.4f | %.2f 1/s | %.4f | %.2f× |" % [ref.roll, nd.call(ref.roll, ref.b, ref.V),
		roll, nd.call(roll, b, V), nd.call(roll, b, V) / nd.call(ref.roll, ref.b, ref.V)])
	print("| Dutch roll (L = b) | %.2f rad/s, ζ %.2f | %.4f | %.2f rad/s, ζ %.2f | %.4f | %.2f× |\n" % [ref.dr_wn, ref.dr_zeta, nd.call(ref.dr_wn, ref.b, ref.V),
		dr_wn, eq.dutch_roll.zeta, nd.call(dr_wn, b, V), nd.call(dr_wn, b, V) / nd.call(ref.dr_wn, ref.b, ref.V)])
	var j: PackedFloat64Array = model.inertia
	print("Roll inertia ratio Ixx/(m·b²): sim %.4f, 25e swing test %.4f (0.089 kg·m², 1.959 kg, 1.27 m)\n" % [j[0] / (model.mass_kg * b * b), 0.089 / (ref.m * ref.b * ref.b)])
