## L11a: fixed offline placement, clipped to the current field; opaque geometry only, no simulation nodes.
extends RefCounted

const Frames = preload("res://render/frames.gd")
const ShaderClock = preload("res://render/shader_clock.gd")
const SHADER: Shader = preload("res://render/near_grass.gdshader")
const DATA_PATH: String = "res://data/fields/grass.json"
const RADIUS_M: float = 30.0
const CLEARANCE_M: float = 0.4 # estimated; exceeds the widest clump at maximum scale plus shader sway
const COUNT: int = 6000
const BLADES: int = 7


## Hash input is plain integer ASCII, also generated by tools/grass/place.py.
static func validated_rows(raw: Variant) -> Array:
	if not raw is Dictionary or raw.get("format", "") != "openrc-grass v1" or raw.get("radius_mm", 0) != 30000:
		return []
	var rows: Variant = raw.get("rows", null)
	if not rows is Array or rows.size() != COUNT:
		return []
	var canonical: String = ""
	var seen: Dictionary = {}
	for row: Variant in rows:
		if not row is Array or row.size() != 4:
			return []
		for value: Variant in row:
			if not (value is int or value is float) or not is_finite(float(value)) or float(value) != floorf(float(value)):
				return []
		if absf(float(row[0])) > 30000.0 or absf(float(row[1])) > 30000.0:
			return []
		var n: int = int(row[0])
		var e: int = int(row[1])
		if absi(n) > 30000 or absi(e) > 30000 or n * n + e * e > 30000 * 30000:
			return []
		if row[2] < 0 or row[2] > 65535 or row[3] < 0 or row[3] > 255:
			return []
		var key: Vector2i = Vector2i(n, e)
		if seen.has(key):
			return []
		seen[key] = true
		canonical += "%d,%d,%d,%d\n" % [n, e, int(row[2]), int(row[3])]
	if canonical.sha256_text() != raw.get("rows_sha256", ""):
		return []
	return rows


## Rectangles come from the validated field; any mown/runway surface excludes the full clump footprint.
static func accepts(north: float, east: float, field: Dictionary) -> bool:
	var on_rough: bool = false
	for surface: Dictionary in field.surfaces:
		var dn: float = absf(north - float(surface.center_north))
		var de: float = absf(east - float(surface.center_east))
		var hn: float = float(surface.width_north_south) * 0.5
		var he: float = float(surface.length_east_west) * 0.5
		if surface.type == "rough":
			on_rough = on_rough or (dn <= hn - CLEARANCE_M and de <= he - CLEARANCE_M)
		elif dn <= hn + CLEARANCE_M and de <= he + CLEARANCE_M:
			return false
	return on_rough


## Seven separate opaque triangles. Roots are y=0; heights 0.10–0.18 m and footprint <0.2 m are artistic estimates.
static func clump_mesh() -> ArrayMesh:
	var vertices: PackedVector3Array = PackedVector3Array()
	var normals: PackedVector3Array = PackedVector3Array()
	var uvs: PackedVector2Array = PackedVector2Array()
	for i: int in BLADES:
		var angle: float = float(i) * TAU / float(BLADES)
		var out: Vector3 = Vector3(cos(angle), 0.0, sin(angle))
		var side: Vector3 = Vector3(-out.z, 0.0, out.x)
		var base: Vector3 = out * (0.025 + 0.012 * float(i % 3))
		var half_width: float = 0.009 + 0.003 * float(i % 2)
		vertices.append(base - side * half_width)
		vertices.append(base + out * 0.045 + Vector3.UP * (0.10 + 0.02 * float(i % 5)))
		vertices.append(base + side * half_width)
		normals.append_array(PackedVector3Array([Vector3.UP, Vector3.UP, Vector3.UP]))
		uvs.append_array(PackedVector2Array([Vector2.ZERO, Vector2(0.5, 1.0), Vector2(1.0, 0.0)]))
	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = vertices
	arrays[Mesh.ARRAY_NORMAL] = normals
	arrays[Mesh.ARRAY_TEX_UV] = uvs
	var mesh: ArrayMesh = ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return mesh


## Pure placement boundary, inspectable with the dummy renderer (MultiMesh transform readback is unavailable there).
static func clipped_chunks(field: Dictionary, rows: Array) -> Array:
	var chunks: Array = [[], [], [], []]
	for row: Array in rows:
		var north: float = float(field.pilot.north) + float(row[0]) * 0.001
		var east: float = float(field.pilot.east) + float(row[1]) * 0.001
		if not accepts(north, east, field):
			continue
		var chunk: int = (0 if row[0] < 0 else 2) + (0 if row[1] < 0 else 1)
		chunks[chunk].append([north, east, int(row[2]), int(row[3])])
	return chunks


static func build(field: Dictionary, ground: ShaderMaterial) -> Node3D:
	var result: Node3D = Node3D.new()
	result.name = "NearGrass"
	var file: FileAccess = FileAccess.open(DATA_PATH, FileAccess.READ)
	var rows: Array = validated_rows(JSON.parse_string(file.get_as_text())) if file != null else []
	if rows.is_empty():
		push_warning("L11a grass placement missing or invalid; field remains available without grass")
		return result
	ShaderClock.register() # standalone field builds must work without main.gd's environment setup
	var material: ShaderMaterial = ShaderMaterial.new()
	material.shader = SHADER
	for uniform: Dictionary in SHADER.get_shader_uniform_list():
		var parameter: StringName = StringName(uniform.name)
		if parameter == &"fade_start_m" or parameter == &"fade_end_m":
			continue
		var value: Variant = ground.get_shader_parameter(parameter)
		if value != null:
			material.set_shader_parameter(parameter, value)
	var mesh: ArrayMesh = clump_mesh()
	mesh.surface_set_material(0, material)
	var chunks: Array = clipped_chunks(field, rows)
	var total: int = 0
	for k: int in 4:
		var points: Array = chunks[k]
		if points.is_empty():
			continue
		var mm: MultiMesh = MultiMesh.new()
		mm.transform_format = MultiMesh.TRANSFORM_3D
		mm.mesh = mesh
		mm.instance_count = points.size()
		for i: int in points.size():
			var point: Array = points[i]
			var yaw: float = float(point[2]) * TAU / 65536.0
			var size: float = 0.75 + 0.5 * float(point[3]) / 255.0
			var basis: Basis = Basis(Vector3.UP, yaw).scaled(Vector3.ONE * size)
			mm.set_instance_transform(i, Transform3D(basis, Frames.ned_to_render([point[0], point[1], 0.0])))
		var node: MultiMeshInstance3D = MultiMeshInstance3D.new()
		node.name = "grass_%d" % k
		node.multimesh = mm
		node.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		node.custom_aabb = mm.get_aabb().grow(0.05) # bounded 0.035 m wind sway; fade only shrinks the mesh
		result.add_child(node)
		total += points.size()
	result.set_meta("clumps", total)
	return result
